### ISSUE TITLE
Make `(MonadIO m => m ())` an instance of `FromBuilder`?

### ISSUE THREAD

**Issue by howsiwei** [cdornan/fmt#11]
So that I can just use `fmt` instead of `liftIO . fmt`.

**Comment by ChShersh** [comment]
@howsiwei Thanks for your interest in `fmt` library! But this instance won't be really good, because instead of instance of type class for some data type it now becomes instances of one type class for another type class. It's very often desire to have `IO` functions which automatically work for any IO... I'm not sure what @neongreen thinks about it. I can see other alternative solutions:

1. Add `fmtIO = liftIO . fmt` function.
2. Wait for #5 to be implemented.

**Comment by neongreen** [comment]
I think that such an instance might cause people trouble even if we make it `OVERLAPPABLE`. I'm not sure about that, though.

**Comment by cdornan** [comment]
I like the `fmtIO = liftIO . fmt` idea &mdash; shouldn't break stuff and gets the job done, now?

**Comment by howsiwei** [comment]
Yes, `fmtIO = liftIO . fmt` works for me. Feel free to close this issue.
