### ISSUE TITLE
Add duration formatter

### ISSUE THREAD

**Issue by chshersh** [cdornan/fmt#12]
I would really appreciate some formatter for ranges like `1w2d3h4m` like this one:

```haskell
durationF :: Natural -> Builder
```

But I would like to have an ability to easily  interpret `9623` as `9623 minutes` or `9623 seconds` and format in either `160h23m` or `160m23s`. Dunno how the resulting interface should look like...

**Comment by ChShersh** [comment]
Seems relevant: 

* https://github.com/serokell/o-clock/issues/19

**Comment by neongreen** [comment]
There's `diffF` already but I agree that we should have something like this.

**Comment by neongreen** [comment]
Though obviously baking-in 8 hour days won't be good

**Comment by neongreen** [comment]
Maybe we can indeed use the o-clock idea with series. I think that instead of type-level lists we can just have a list of predefined `(Builder, Int)` pairs. @ChShersh what do you think?

**Comment by ChShersh** [comment]
@neongreen Well, since there's `o-clock` I don't actually need `durationF` formatter anymore. `seriesF` is enough to me. I won't use this formatter on something that doesn't represent time. And if I need time I probably will use `o-clock`. `seriesF` is already a good reason for me to use package like `o-clock`. Though, `o-clock` probably should have `Buildable` instance but at this moment it's not clear for me which exact `Buildable` should it use...

**Comment by cdornan** [comment]
It looks like we don't need this &mdash; please feel free to reopen if you disagree.
