### ISSUE TITLE
Switch to 'Display' from 'Buildable'

### ISSUE THREAD

**Issue by chshersh** [cdornan/fmt#13]
Looks like [`display` package](https://hackage.haskell.org/package/display) provides more efficient conversion. Also, `text-show` is not maintained.

See [this conversation](https://www.reddit.com/r/haskell/comments/7q8kkd/uniform_buildable_type_class_for_formatting/dsntm4n/) for reference.

**Comment by ChShersh** [comment]
After some thoughts and discussions it become clear that this migration is not an option, unfortunately, because `ByteString.Builder` doesn't have `IsString` instance (and probably can't have). So this issue is postponed untill `Builder` from `text-show` will be moved to `text` package:

* https://github.com/haskell/text/issues/214

**Comment by neongreen** [comment]
See https://github.com/aelve/fmt/issues/17#issuecomment-374794265

**Comment by neongreen** [comment]
Also see #21.
